services:

  php-fpm:
    build:
      context: ./docker/php-fpm
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    image: 8.2-fpm-bookworm
    volumes:
      - ./:/var/www/html
    user: "root:root"
    command: php-fpm