services:

  php-fpm:
    build:
      context: ./docker/php-fpm
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    volumes:
      - ./:/var/www/html
      - ./docker/php-fpm/logs/commandhistory:/commandhistory
    user: "root:root"
    command: php-fpm